#define GTK3_TETRADACTYL_LIB "libtetradactyl-gtk3.so"
#define GTK4_TETRADACTYL_LIB "libtetradactyl-gtk4.so"
#define QT5_TETRADACTYL_LIB "libtetradactyl-qt5.so"
#define QT6_TETRADACTYL_LIB "libtetradactyl-qt6.so"
#define GTK3_LIB "libgtk-3"
#define GTK4_LIB "libgtk-4"
#define QT5_LIB "libQt5Widgets"
#define QT6_LIB "libQt6Widgets"
